spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  datasource:
    url: jdbc:h2:mem:prodDB
    driver-class-name: org.h2.Driver
    username: user
    password: pass
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 500000
      max-lifetime: 1200000
      connection-timeout: 30000

  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false

logging:
  level:
    root: info
    io.github.balasis.taskmanager: TRACE
    org.springframework.transaction.interceptor: TRACE
