spring:
  datasource:
    url: ${FLYWAY_DB_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${FLYWAY_DB_USERNAME}
    password: ${FLYWAY_DB_PASSWORD}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 500000
      max-lifetime: 1200000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    root: info
    io.github.balasis.taskmanager: TRACE
    org.springframework.transaction.interceptor: info
    org.flywaydb: DEBUG
