name: maintenance-ci-cd

on:
  push:
    paths:
      - 'task-manager-maintenance/**'
      - 'task-manager-contracts/**'
  workflow_dispatch:

jobs:
  test_maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build contract dependency first
        run: |
          mvn -f task-manager-contracts/pom.xml clean install

      - name: Build and run tests with H2
        run: |
          mvn -f task-manager-maintenance/task-manager-maintenance-blobcleaner/pom.xml clean test \
            -Dspring.profiles.active="dev-h2"

  deploy_maintenance:
    runs-on: ubuntu-latest
    needs: test_maintenance
    if: ${{ needs.test_maintenance.result == 'success' && github.ref == 'refs/heads/main' && false }}

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build contract dependency first
        run: |
          mvn -f task-manager-contracts/pom.xml clean install

      - name: Create package
        run: |
          mvn -f task-manager-maintenance/task-manager-maintenance-blobcleaner/pom.xml clean package -DskipTests

      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: anstaskmanageracr-g3bwdtdrb8h9bfem.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build Docker image
        run: |
          docker build -t anstaskmanageracr-g3bwdtdrb8h9bfem.azurecr.io/taskmanager-maintenance:$IMAGE_TAG task-manager-maintenance/task-manager-maintenance-blobcleaner

      - name: Push Docker image
        run: |
          docker push anstaskmanageracr-g3bwdtdrb8h9bfem.azurecr.io/taskmanager-maintenance:$IMAGE_TAG

      - name: Change the image of maintenance web app service
        run: |
          az webapp config container set \
            --name taskmanager-rg-maintenance \
            --resource-group TaskManager-RG \
            --container-image-name anstaskmanageracr-g3bwdtdrb8h9bfem.azurecr.io/taskmanager-maintenance:$IMAGE_TAG \
            --container-registry-url https://anstaskmanageracr-g3bwdtdrb8h9bfem.azurecr.io
